title: Values
slug: values
date: 12-21-2025
author: Land of Enchantment Games
body: |

  ---

  ## Values

  ### Homegrown
  Built here.

  Certified non-GMO organic.
  Made with ❤️.

  ### Handmade
  Handmade `code`.
  Handmade `pixels`.
  Handmade `music`.
  Handmade `stories`.

  By humans, for humans.

  ### Libre
  Built on free and open-source software.

  ### What We Don’t Do
  - **NO AI slop**
  - **NO pay-to-win**
  - **NO microtransactions**
  - **NO advertisements**
  - **NO spyware or invasive anti-cheat**

  ### Ownership
  Not for rent.
  You buy it **once** → You own it **forever**.

  ### Respect
  We respect the player’s:
  - **`Time`**
  - **`Freedom`**
  - **`Intelligence`**
  - **`Attention`**
  - **`Humanity`**

  We do **not** manipulate, addict, or extract.

  ### Principle
  **Integrity wins.**
